spring.application.name=Java-Spring-JPA-exam

#MySQL config
spring.datasource.url=${MYSQL_TEST_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

#Hibernate config
#Use create-drop to start with a clean database when a test is initiated.
spring.jpa.hibernate.ddl-auto=create-drop
